title: Logesh G
logo: /assets/img/pic.png
description: > # text below the logo image
  <strong>Email: logeshg248@gmail.com</strong>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/logeshg2/" target="_blank">LinkedIn</a>  |  <a href="https://github.com/logeshg2" target="_blank">GitHub</a> | 
  <a href="https://logeshg2.github.io/" target="_blank">Website</a> | <a href="assets/docs/Resume.pdf" target="_blank">Resume</a> 
  <p style="text-align:center;">| <a href="https://www.youtube.com/@LogRobotics" target="_blank">Youtube</a> |</p>
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
plugins:
  - jemoji
